version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - generator-api
    networks:
      - interactive-edu

  frontend:
    build:
      context: ../apps/gateway-frontend
      dockerfile: ../../infra/Dockerfile.frontend
    environment:
      - GEN_API_URL=http://generator-api:4000
    expose:
      - "3000"
    networks:
      - interactive-edu

  generator-api:
    build:
      context: ../apps/generator-api
      dockerfile: ../../infra/Dockerfile.api
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PORT=4000
    expose:
      - "4000"
    networks:
      - interactive-edu

networks:
  interactive-edu:
    driver: bridge 